config/routes.rb
class AgentConstraint
  def self.matches?(request)
    Rails.env.development? && request.user_agent =~ /Mobile/
  end
end


Cg2App::Application.routes.draw do

  constraints(:host => "caregaroo.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "www.caregaroo.com" }.to_s
    }
  end

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/show"

  # app routes
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#login", :as => "login"
  get "register" => "register#new"
  post "register" => "register#create", :as => "register"
  post "register_new" => "register#new"
  get "register/success" => "register#success", :as => "register_success"
  get "profile" => "profile#info", :as => "profile"
  get "profile/edit" => "profile#edit_info", :as => "edit_info_profile"
  get "profile/:user_id" => "profile#info", :as => "user_info_profile"
  post "profile" => "profile#update_info", :as => "update_info_profile"
  get "news" => "posts#index", :as => "news"
  get "news/:post_id/comments" => "posts#comments", :as => "post_commments"
  get "news/:post_id" => "posts#full_post", :as => "post"
  delete "news/:post_id" => "posts#destroy", :as => "post_delete"
  get "comment/:comment_id" => "comments#full_comment", :as => "comment"
  delete "comment/:comment_id" => "comments#destroy", :as => "comment"
  get "members" => "members#index", :as => "members"
  put "members/:user_id" => "members#update", :as => "members_update"
  delete "members/:user_id" => "members#delete", :as => "members_delete"
  get "invite" => "invitations#index", :as => "invite"
  get "invite/success" => "invitations#success", :as => "success_invitation"
  post "invite/send" => "invitations#create", :as => "send_invitation"
  post "messages/reply" => "messages#reply", :as => "reply_message"
  get "unsubscribe" => "notifications#unsubscribe", :as => "unsubscribe"
  get "network/edit" => "network#edit", :as => "network_edit"
  get "network/switch" => "network#switch", :as => "network_switch"
  put "network/switch_save" => "network#switch_save", :as => "network_switch_save"
  post "network/save" => "network#save", :as => "network_save"

  post "signup/create" => "signup#create", :as => "signup_create"
  get "signup/success" => "signup#success", :as => "signup_success"
  get "signup/:invitation_token" => "signup#new", :as => "signup_with_token"

  # marketing routes
  #post "pilot_signups/:id" => "pilot_signups#destroy", :as => "signup_delete"
  #get "download/ebook" => "download#ebook", :as => "download_ebook"
  #get "download/faq" => "download#faq", :as => "download_faq"
  #get "admin" => "pilot_signups#index", :as => "admin"
  post "signup" => "register#signup", :as => "signup"
  match "product" => "home#product"
  #match "home_new" => "home#home_new", :as => "home_new"

  match 'fb_tab' => "landing#fb_tab", :as => 'fb_tab'
  get 'fb_tab_post' => "landing#fb_tab_post"
  
  resources :comments do
    # the call in app/views/events/_comment.mobile.erb has method: :delete set but it still comes in as get 
    get 'remove', on: :member, as: :destroy
  end
  resources :events do
    delete 'cancel', on: :member
    put 'update_user', on: :member
  end
  resources :messages
  resources :password_resets
  resources :pilot_signups
  resources :posts
  resources :sessions

  match "debugger/:action(/:id)" => "debug", :as => :debug
  
  get "users/current"
  
  # backoffice routes
  namespace :backoffice do
    get '', :to => 'dashboard#index', :as => '/'
    resources :users, :networks, :news, :events, :invitations, :activities, :landpage
  end

  mount Resque::Server, :at => "/resque"
  
  constraints(AgentConstraint) do
   root :to => "mobile#index", :as => "root"
  end
  root :to => "home#index", :as => "root"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @page = 'home'
    @current_user = current_user
    render 'index', :layout => "marketing"
  end

  def product
    @page = 'product'
    render 'product', :layout => "marketing"
  end  
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="span6"><img src="assets/ladies.jpg" class="responsive-bg"></div>  
  <div class="span5 offset1">
    <p class="intro" style="margin-top:20px; text-align:center;"><span style="font-weight:bold;font-size:28px">Care better, together</span><br/>Get the support you need<br/>from family and friends</p>
    <div style="margin-top:30px; width:100%; padding:0 10px;">
      <div>
      <form class="well" action="/register_new" method="post">
        <span class="help-block" style="font-size:20px; font-style:italic; margin:10px 10px 20px 10px;">Create your free private network</span>
        <input type="text" class="span4" name="network_for_who" autocomplete="off"  maxlength="35" placeholder="Who are you caring for?">
        <% if @current_user %>
          <input type="text" href="#point-sign-out" class="span4" name="email" autocomplete="off" maxlength="35" value="<%= @current_user.email %>", readonly="readonly">
        <% else %>
          <input type="text" class="span4" name="email" autocomplete="off" maxlength="35" placeholder="Your email address?">
        <% end %>
        <!--input type="password" class="span4" name="password" placeholder="Choose your password"-->
        <div style="margin-top:20px;height:30px;">
        <% if @current_user %>
        <%# link_to "Log out", logout_path %>
        <% else %>
        <a href="/login" rel="nofollow">Already have an account? Sign in.</a>
        <% end %>
        <div class="pull-right"><button id="register_submit pull-right" type="submit" class="btn btn-warning">Create a Network</button></div>
        </div>
      </form>
      </div>
    </div>
  </div>
</div>

<section class="row" style="margin-top:20px">
  <div class="span4">
    <div>
      <div id="calendar_img"></div>
      <div style="padding-right:15px;"><p class="title">Coordinate Care</p><p>Are you caring for a loved one with health issues? Do you wish you could enlist more help from family and friends? <font class="blueFont">Caregaroo</font> provides simple-to-use online tools to engage the support of your care network.</p></div>
    </div>
  </div>
  <div class="span4">
    <div>
      <div id="news_img"> </div>
      <div style="padding-right:15px;"><p class="title">Share News</p><p>Is it a challenge to keep everyone informed? With <font class="blueFont">Caregaroo</font> it is easy to share news related to changes in health, upcoming events and activities needing volunteers, in a secure and private space.</p></div> 
    </div>
  </div>
  <div class="span4">    
    <div>
      <div id="email_img"></div>
      <div style="padding-right:15px;"><p class="title">Anytime, Anywhere</p><p>Want to send an update from the doctor's office or communicate change of plans when you are on the go? No problem. With <font class="blueFont">Caregaroo</font> mobile web, you can enjoy the benefits wherever you are.</p></div>
     </div>
  </div>
</section>
<hr/>
<div class="row">
  <div class="span offset1">
    <div id="marketingVideo" class="video-wrapper ">
      <div id="thevideo" class="video-container">
        <object width="640" height="360">
          <param name="movie" value="http://www.youtube.com/v/zzq2e8Fbuxk?version=3&showinfo=0&hl=en&fs=1"></param>
          <param name="allowFullScreen" value="true"></param>
          <param name="allowscriptaccess" value="always"></param>
          <param name="wmode" value="transparent"></param>
          <embed wmode="transparent"  src="http://www.youtube.com/v/zzq2e8Fbuxk?version=3&showinfo=0&hl=en&fs=1" type="application/x-shockwave-flash" width="640" height="360" allowscriptaccess="always" allowfullscreen="true"></embed>
    </object> 
      </div>
    </div>
  </div>
  <div class="span2">
    <div style="margin-top:30px; text-align:center; width:160px">
    <p class="intro">Make caring easy with <font class="blueFont">Caregaroo</font></p><br/>
    <form action="/product" method="get"><button class="btn btn-warning" onclick="">Learn More</button></form>
    <div style="margin-top:20px; width:200px">
      <ul style="list-style:none outside none;">
      <li style="float:left; margin:8px 0"><a href="https://twitter.com/CaregarooApp" class="twitter-follow-button" data-show-screen-name="false" data-show-count="false">Tweet</a></li>
      <li style="float:left; margin-left:10px"><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.facebook.com%2FCaregaroo&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:80px; height:21px;margin-top:8px" allowTransparency="true"></iframe></li>
      </ul>
    </div>      
    </div>
  </div>
</div>

<div style="display:none;">
    <div id="point-sign-out">
      <h1>Different e-mail?</h1>
      <center>
        <p>
          If you'd like to create another network using a different e-mail you must first log out by clicking the Log out button above.
        </p>
          <br>
          <a href="javascript:$.fancybox.close()" ><button class="btn btn-warning" type="button">OK</button></a>
      </center>
    </div>
  </div>

<script type="text/javascript">
$('input[name=email][readonly]').fancybox({
    autoDimensions: false,
    width: 400,
    height: 200,
    overlayColor: "#FFF",
    opacity: 0.8,
  });
  </script>

app/views/home/index.mobile.erb
<div class='current' id='home'>
  <div class='toolbar'>
    <h1>Caregaroo</h1>
    <a href="#login" class="button slideup">Login</a>
  </div>
</div>
<%= form_for @session, :url => sessions_path, :method => :post, :html => { :id => 'login' } do |f| %>
  <div class="toolbar">
    <h1>Login</h1>
  </div>
  <ul class="rounded">
    <li><input name="email" value="" type="text" placeholder="Email Address"></li>
    <li><input name="password" value="" type="password" placeholder="Password"></li>
  </ul>
  <a class="whiteButton submit">Login</a>
  <a class="grayButton goback">Cancel</a>
<% end %>

app/views/home/index_old.html.erb
<div id="header">
	<div id="marketingVideo">
		<iframe id="ytvideo" class="youtube-player" width="498" height="310" 
			src="http://www.youtube.com/embed/zzq2e8Fbuxk?html5=1&rel=0&autoplay=0&enablejsapi=1&wmode=transparent&showinfo=0" wmode="Opaque"
			frameborder="0" allowfullscreen="true"></iframe>
	</div>
	<div id="topSignup" class="quickSignup right"> 
		<h1 id="homeCareTitle">Home Care Coordination</h1>
		<h3 id="homeCareDesc"><font class="blueFont">Caregaroo</font><font style="font-weight:normal"> is a private secure network for families to share news, coordinate home care and assist loved ones living independently.</font></h3> 
		<div id="tryForFreeBtn">
			<a href="register" onclick="_gaq.push(['_trackEvent', 'Links', 'Try it free', 'Try it free - Home Page Top'])" title="Try Caregaroo Free"></a>
		</div>
	</div> 
</div>
<div id="benefits" class="grid_14 clearfix"> 
<ul>
<% if cookies[:ebook] == "1" %> 
<li><a href="/download/ebook" onclick="_gaq.push(['_trackEvent', 'Links', 'Download e-Book', 'Download e-Book - Home Page']);" title="Download Caregaroo's eBook" id="ebookLink"><img src="img/downloadCaregaroosEbook.jpg"alt="time saver icon" /></a></li>
<% else %>
<li><a href="#downloadebook" onclick="_gaq.push(['_trackEvent', 'Links', 'Download e-Book', 'Download e-Book - Home Page']);" title="Download Caregaroo's eBook" class="custom" id="ebookLink"><img src="img/downloadCaregaroosEbook.jpg"alt="time saver icon" /></a></li>
<% end %>
<li class="second"><a href="#demo" onclick="_gaq.push(['_trackEvent', 'Links', 'Request Demo', 'Request demo - Home Page']);" title="Request A Demo" class="custom" id="demoLink"><img src="img/requestADemo.jpg" alt="requestADemo"/></a></li>
<li class="third"><a href="/product" onclick="_gaq.push(['_trackEvent', 'Links', 'Product Tour', 'Product Tour - Home Page']);" title="Take A Tour" id="tourLink"><img src="img/TakeATourHomecare.jpg" alt="Take A Tour" /></a></li> </ul> 
<img class="separator" src="img/line.png" alt="separator line" />
</div> 
<div id="features" class="grid_14 clearfix"> <div class="tagline grid_14"> <h1>Key Benefits</h1> <p></p></div>
<div id="feature1" class="feature grid_14">
<div class="featureLeft grid_6">
<img class="featureImage" src="img/feature1.jpg" alt="full deeplink support"/>
</div>
<div class="featureDetails"> <h2>Are you caring for a loved one with health issues?</h2> <p>Is it a constant challenge to keep friends and
family informed? Do you wish you could enlist more help from other members of the care circle? <font class="blueFont">Caregaroo</font>
provides simple-to-use online tools to help you communicate and coordinate care for your loved ones.</p>
</div>
</div> 
<div id="feature2" class="feature grid_14">
<div class="featureRight grid_6">
<img class="featureImage" src="img/feature2.jpg" alt="full deeplink support" /> </div>
<div class="featureDetails withIcon"> <h2>Share News</h2> <p>Create an online community around your
loved one and invite friends, family and other members of the care community to join. Exchange news and share updates on health, upcoming needs and daily
activities. With <font class="blueFont">Caregaroo</font> it is now easy to keep everyone informed.</p> </div>
</div>
<div id="feature3" class="feature grid_14">
<div class="featureLeft grid_6">
<img class="featureImage" src="img/feature3.jpg" alt="coordinate care" />
</div>
<div class="featureDetails"> <h2>Coordinate Care</h2> <p>List activities and ask members of the care
community volunteer to get things done. Need a ride to a medical appointment or help with meal
preparation? With <font class="blueFont">Caregaroo</font>, it is easy to communicate the support you need and organize contributors from the community towards improving your loved one’s quality of life.</p>
</div>
</div>
<div id="feature4" class="feature grid_14">
<div class="featureRight grid_6">
<img class="featureImage" src="img/feature4.jpg" alt="user editable playlist" />
</div>
<div class="featureDetails"> <div class="featureDetails"><h2>Works with Email</h2> <p>Since it’s not
possible to stay logged into <font class="blueFont">Caregaroo</font> around the clock, you can choose to be notified via email when
something important happens in your network. You can also send updates and respond to messages directly
from your email. Can’t find that old email you are looking for? No problem, <font class="blueFont">Caregaroo</font> makes it easy to
find and track all communications.</p> </div>
</div>
<div id="feature3" class="feature grid_14">
<div class="featureLeft grid_6">
<img class="featureImage" src="img/feature5.jpg" alt="coordinate care" />
</div>
<div class="featureDetails"> <div id="coming_soon_icon"></div><h2>Find Professional Caregivers</h2> <p>Search and find professional care
providers with the skills you need. View their professional profiles, area of expertise and previous
employment history. Since all listed professionals have been members of the <font class="blueFont">Caregaroo</font> network, you can
request first-hand references from their previous employers with a click of a button!</p>
</div>
</div>
</div>
</div>
<div style="display:none">
	<div id="downloadebook" class="popup">
		<%= form_for PilotSignup.new, :url => signup_path, :remote => true, :html => { :id => 'download_ebook_form' } do |f| %>
		  <div id="ebookError" class="error" style="display:none">* Please enter a valid email</div>
		  <%= f.hidden_field :signup_type, :value => "ebook" %>
		  <%= f.text_field :first_name, "title" => "Enter your first name", :autocomplete => 'off', :class => "rounded shadowBtm signup_first_name" %>
		  <%= f.text_field :last_name, "title" => "Enter your last name", :autocomplete => 'off', :class => "rounded shadowBtm signup_last_name" %>
		  <%= f.text_field :email, "title" => "Enter your email address", :autocomplete => 'off', :class => "rounded shadowBtm signup_email" %>
		  <p><%= f.submit :value => "Download" %></p>
		<% end %>
	</div>
</div>
<div style="display:none">
	<div id="demo" class="popup">
		<%= form_for PilotSignup.new, :url => signup_path, :remote => true, :html => { :id => 'demo_form' } do |f| %>
		  <div id="demoError" class="error" style="display:none">* Please enter a valid email</div>
		  <%= f.hidden_field :signup_type, :value => "demo" %>
		  <%= f.text_field :email, "title" => "Enter your email address", :autocomplete => 'off', :class => "rounded shadowBtm signup_email" %>
		  <p><%= f.submit :value => "Request" %></p>
		<% end %>
	</div>
</div>
</div>

app/views/home/product.html.erb
<div class="row">
	<div style="width:260px; max-width:100%; margin:0 auto;">
<ul class="nav nav-pills">
  <li class="active">
    <a href="#news" data-toggle="tab">News Stream</a>
  </li>
  <li><a href="#calendar" data-toggle="tab">Calendar</a></li>
  <li><a href="#thanks" data-toggle="tab">Thanks</a></li>
</ul>
</div>
</div>

<div class="span12 tab-content" id="productTab">
	<div class="tab-pane active" id="news">
		<div style="text-align:center"><%= image_tag "CareNewsStream.png", :alt => "News Stream" %></div>	
		<div class="span10 offset1">
			<p class="title">News Stream</p>
			With <font class="blueFont">Caregaroo</font> you can post real-time status updates about your loved one. With just one post everyone can be informed at once. Ask friends, family and professional care providers to post news updates on how your loved one is doing after each visit. With News Stream you can easily stay connected.
		</div>
	</div>
	<div class="tab-pane" id="calendar">
		<div style="text-align:center"><%= image_tag "careCalendar.png", :alt => "Calendar" %></div>	
		<div class="span10 offset1">
			<p class="title">Calendar</p>
			Post all the tasks you need help with and invite members of your care circle to volunteer their help. You would be surprised how willing people are to help when there is an easy and convenient way to	coordinate their time and contribution.
		</div>
	</div>
	<div class="tab-pane" id="contributions">
		<div style="text-align:center"><%= image_tag "Contributions.png", :alt => "Contributions" %></div>	
		<div class="span10 offset1">
			<p class="title">Contributions</p>
			With <font class="blueFont">Caregaroo</font>, all relevant member profile information are tracked and viewable by all. This information includes members' contact information, activities, tasks performed as well as upcoming commitments. At a glance everyone can see the extent and nature of the contributions that each member has been providing throughout time.
		</div>
	</div>
	<div class="tab-pane" id="thanks">
		<div style="text-align:center"><%= image_tag "ThankCaregivers.png", :alt => "Thanks" %></div>	
		<div class="span10 offset1">
			<p class="title">Thanks</p>
			Say "<span style="font-style:italic">Thanks</span>!" to those who make a significant contribution and let everyone know how much you value their help. Express your appreciation publically and frequently, to keep everyone engaged in the process of care giving. All the <span style="font-style:italic">Thanks</span> messages ever received by each member is a testament to all the contribution they have made over time.
		</div>
	</div>
</div>

app/views/home/product_old.html.erb
<div id="features" class="grid_14 clearfix">
<div id="productFeature1" class="feature grid_14">
	<div class="featureRight grid_6">
		<a href="/img/screenshot_news.jpg" onclick="_gaq.push(['_trackEvent', 'Links', 'Screenshot - News Stream', 'Screenshot - News Stream']);" class="single_image" id="screenShotNewsStream"><img class="productImage" src="img/HomecareNewsStream.jpg" alt="New Stream" /> </a>
	</div>
	<div class="featureDetails withIcon"> 
	<h2>News Stream</h2> 
	<p>With <font class="blueFont">Caregaroo</font> you can post real-time status updates about your loved one. With just one post everyone can be informed at once. 
		Ask friends, family and professional care providers to post news updates on how your loved one is doing 
		after each visit. With News Stream you can easily stay connected.</p> 
	</div>
</div>
<div id="productFeature2" class="feature grid_14">
<div class="featureLeft grid_6">
	<a href="/img/screenshot_calendar.jpg" onclick="_gaq.push(['_trackEvent', 'Links', 'Screenshot - Calendar', 'Screenshot - Calendar']);" class="single_image" id="screenShotCalendar"><img class="productImage" src="img/HomecareCalendar.jpg" alt="Homecare Calendar" /></a>
</div>
<div class="featureDetails"> 
	<h2>Calendar</h2> 
	<p>Post all the tasks you need help with and invite members of your care circle to volunteer their help.
		You would be surprised how willing people are to help when there is an easy and convenient way to 
		coordinate their time and contribution.	</p>
</div>
</div>
<div id="productFeature3" class="feature grid_14">
	<div class="featureRight grid_6">
		<a href="/img/screenshot_tasks.jpg" onclick="_gaq.push(['_trackEvent', 'Links', 'Screenshot - Vital Info', 'Screenshot - Vital Info']);" class="single_image" id="screenShotTasks"><img class="productImage" src="img/HomecareVitalInformation.jpg" alt="Vital Information" /></a>
	</div>
	<div class="featureDetails withIcon"> 
	<h2>Contributions</h2> 
	<p>With <font class="blueFont">Caregaroo</font>, all relevant member profile information are tracked and viewable by all. This information includes members' contact information, activities, tasks performed as well as upcoming commitments. At a glance everyone can see the extent and nature of the contributions that each member has been providing throughout time.</p>
	</div>
</div>
<div id="productFeature4" class="feature grid_14">
	<div class="featureLeft grid_6">
		<a href="/img/screenshot_thanks.jpg" onclick="_gaq.push(['_trackEvent', 'Links', 'Screenshot - Thanks', 'Screenshot - Thanks']);" class="single_image" id="screenShotThanks"><img class="productImage" src="img/HomecareThanks.jpg" alt="Thanks Message" /> </a>
</div>
<div class="featureDetails"> 
	<h2>Thanks</h2> 
	<p>Say "<span style="font-style:italic">Thanks</span>!" to those who make a significant contribution and let everyone know how much you value their help. Express your appreciation publically and frequently,
		to keep everyone engaged in the process of care giving. All the <span style="font-style:italic">Thanks</span>
		messages ever received by each member is a testament to all the contribution they have made over time.</p> 
</div>
</div>
</div>