config/routes.rb
class AgentConstraint
  def self.matches?(request)
    Rails.env.development? && request.user_agent =~ /Mobile/
  end
end


Cg2App::Application.routes.draw do

  constraints(:host => "caregaroo.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "www.caregaroo.com" }.to_s
    }
  end

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/show"

  # app routes
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#login", :as => "login"
  get "register" => "register#new"
  post "register" => "register#create", :as => "register"
  post "register_new" => "register#new"
  get "register/success" => "register#success", :as => "register_success"
  get "profile" => "profile#info", :as => "profile"
  get "profile/edit" => "profile#edit_info", :as => "edit_info_profile"
  get "profile/:user_id" => "profile#info", :as => "user_info_profile"
  post "profile" => "profile#update_info", :as => "update_info_profile"
  get "news" => "posts#index", :as => "news"
  get "news/:post_id/comments" => "posts#comments", :as => "post_commments"
  get "news/:post_id" => "posts#full_post", :as => "post"
  delete "news/:post_id" => "posts#destroy", :as => "post_delete"
  get "comment/:comment_id" => "comments#full_comment", :as => "comment"
  delete "comment/:comment_id" => "comments#destroy", :as => "comment"
  get "members" => "members#index", :as => "members"
  put "members/:user_id" => "members#update", :as => "members_update"
  delete "members/:user_id" => "members#delete", :as => "members_delete"
  get "invite" => "invitations#index", :as => "invite"
  get "invite/success" => "invitations#success", :as => "success_invitation"
  post "invite/send" => "invitations#create", :as => "send_invitation"
  post "messages/reply" => "messages#reply", :as => "reply_message"
  get "unsubscribe" => "notifications#unsubscribe", :as => "unsubscribe"
  get "network/edit" => "network#edit", :as => "network_edit"
  get "network/switch" => "network#switch", :as => "network_switch"
  put "network/switch_save" => "network#switch_save", :as => "network_switch_save"
  post "network/save" => "network#save", :as => "network_save"

  post "signup/create" => "signup#create", :as => "signup_create"
  get "signup/success" => "signup#success", :as => "signup_success"
  get "signup/:invitation_token" => "signup#new", :as => "signup_with_token"

  # marketing routes
  #post "pilot_signups/:id" => "pilot_signups#destroy", :as => "signup_delete"
  #get "download/ebook" => "download#ebook", :as => "download_ebook"
  #get "download/faq" => "download#faq", :as => "download_faq"
  #get "admin" => "pilot_signups#index", :as => "admin"
  post "signup" => "register#signup", :as => "signup"
  match "product" => "home#product"
  #match "home_new" => "home#home_new", :as => "home_new"

  match 'fb_tab' => "landing#fb_tab", :as => 'fb_tab'
  get 'fb_tab_post' => "landing#fb_tab_post"
  
  resources :comments do
    # the call in app/views/events/_comment.mobile.erb has method: :delete set but it still comes in as get 
    get 'remove', on: :member, as: :destroy
  end
  resources :events do
    delete 'cancel', on: :member
    put 'update_user', on: :member
  end
  resources :messages
  resources :password_resets
  resources :pilot_signups
  resources :posts
  resources :sessions

  match "debugger/:action(/:id)" => "debug", :as => :debug
  
  get "users/current"
  
  # backoffice routes
  namespace :backoffice do
    get '', :to => 'dashboard#index', :as => '/'
    resources :users, :networks, :news, :events, :invitations, :activities, :landpage
  end

  mount Resque::Server, :at => "/resque"
  
  constraints(AgentConstraint) do
   root :to => "mobile#index", :as => "root"
  end
  root :to => "home#index", :as => "root"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  
  attr_accessible :email, :first_name, :last_name, :generate_token, :network_id
  
  validates :email, :presence => true, :email_format => true 
  validates_presence_of :first_name
  validates_presence_of :last_name
  
  belongs_to :network
  belongs_to :sender, :class_name => "User", :foreign_key => "send_id"
  
  before_create :generate_token
  
  def generate_token
    self.token = SecureRandom.base64.tr("+/", "-_")
  end
  
end

app/controllers/backoffice/invitations_controller.rb
class Backoffice::InvitationsController < Backoffice::BaseController

  def index
    # need to include networks because I'll use it to filter records
    @records = Invitation.order("#{sort_column} #{sort_direction}")
                .includes(:sender, :network)
                .paginate(:page => current_page, :per_page => per_page)

    # individual column filtering
    where, arguments = conditions
    @records = @records.where(where, arguments) unless where.blank?

    respond_to do |format|
      format.html
      format.json { render :json => {
          sEcho:                params[:sEcho].to_i,
          iTotalRecords:        Invitation.count,
          iTotalDisplayRecords: @records.total_entries,
          aaData:               format_data(@records)
        }
      }
    end
  end

  private
  # [dataTables]
  def set_columns
    @columns = [
      {:db_name => "users.email",            :human_name => "Email of sender",    :type => "string",      :filter => true},
      {:db_name => "invitations.email",      :human_name => "Email of recipient", :type => "string",      :filter => true},
      {:db_name => "networks.name",          :human_name => "Networks",           :type => "string",      :filter => true},
      {:db_name => "invitations.created_at", :human_name => "Created date",       :type => "date_ranges", :filter => true}
    ]
  end

  # [dataTables]
  def format_data(records)
    records.map do |r|

      sender = %(<a href="#{url_for :controller => 'users', :action => 'show', 
        :id => r.send_id}">#{r.sender.email}</a>) unless r.sender.nil?

      network = %(<a href="#{url_for :controller => 'networks', :action => 'show', 
        :id => r.network_id}">#{r.network.name}</a>) unless r.network.nil?

      [sender, r.email, network, r.created_at.to_s(:long)]

    end
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :require_user
  
  def index
    @page = 'invite'
    @invitation = Invitation.new
  end
  
  def create
    @invitations = Invitation.where("network_id = ? and email = ?", @current_user.network.id, params[:invitation][:email])
    if @invitations.size == 0
      @invitation = Invitation.new(params[:invitation])
      @invitation.send_id = @current_user.id
      @invitation.network_id = @current_user.network.id
    else
      @invitation = @invitations.first
    end
    if @invitation.save
      unless @invitation.email.match /^test\+.*/
        # send invite email
        Resque.enqueue(InvitationMailer, @invitation.id, @current_user.id)
      else
        logger.info ">>>> TEST: NO EMAIL WAS SENT"
      end
      redirect_to success_invitation_path({token: @invitation.token})
    else
      render "index"
    end
  end
  
  def success
  end
  
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/index.html.erb
<h3 class="page_title">Invite new member</h3>
<%= form_for @invitation, :url => send_invitation_path, :method => :post, :html => { :id => 'basic_form' } do |f| %>
<%= render "shared/error_messages", :target => @invitation %>
  <div class="field">
    <%= f.label :email, :class=>"invite_label_text" %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name, :class=>"invite_label_text"  %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, :class=>"invite_label_text"  %>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions"><%= f.submit "Send Invite" , :class =>"form_button", :id=>"submit_invite_btn"%></div>
<% end %>

app/views/invitations/index.js.erb
$.fancybox.close()

app/views/invitations/new.html.erb
<h1>Pilot Program</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<%= form_for @invitations do |f| %>
  <% if @invitations.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @invitations.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions"><%= f.submit "Qualify for Pilot" %></div>
<% end %>
<p><%= link_to "Back to Home", root_path %></p>

app/views/invitations/success.html.erb
<center><h3 class="page_title">Invite email has been sent successfully!</h3></center>
<br/>
<center><%= link_to "Okay", invite_path, :class=>"orange_button_link", :id=>"success_invite_ok_btn" %>
	<input type="hidden" id="token" value="<%=params[:token]%>">
</center>