config/routes.rb
class AgentConstraint
  def self.matches?(request)
    Rails.env.development? && request.user_agent =~ /Mobile/
  end
end


Cg2App::Application.routes.draw do

  constraints(:host => "caregaroo.com") do
    match "(*x)" => redirect { |params, request|
      URI.parse(request.url).tap { |x| x.host = "www.caregaroo.com" }.to_s
    }
  end

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get "calendar/show"

  # app routes
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#login", :as => "login"
  get "register" => "register#new"
  post "register" => "register#create", :as => "register"
  post "register_new" => "register#new"
  get "register/success" => "register#success", :as => "register_success"
  get "profile" => "profile#info", :as => "profile"
  get "profile/edit" => "profile#edit_info", :as => "edit_info_profile"
  get "profile/:user_id" => "profile#info", :as => "user_info_profile"
  post "profile" => "profile#update_info", :as => "update_info_profile"
  get "news" => "posts#index", :as => "news"
  get "news/:post_id/comments" => "posts#comments", :as => "post_commments"
  get "news/:post_id" => "posts#full_post", :as => "post"
  delete "news/:post_id" => "posts#destroy", :as => "post_delete"
  get "comment/:comment_id" => "comments#full_comment", :as => "comment"
  delete "comment/:comment_id" => "comments#destroy", :as => "comment"
  get "members" => "members#index", :as => "members"
  put "members/:user_id" => "members#update", :as => "members_update"
  delete "members/:user_id" => "members#delete", :as => "members_delete"
  get "invite" => "invitations#index", :as => "invite"
  get "invite/success" => "invitations#success", :as => "success_invitation"
  post "invite/send" => "invitations#create", :as => "send_invitation"
  post "messages/reply" => "messages#reply", :as => "reply_message"
  get "unsubscribe" => "notifications#unsubscribe", :as => "unsubscribe"
  get "network/edit" => "network#edit", :as => "network_edit"
  get "network/switch" => "network#switch", :as => "network_switch"
  put "network/switch_save" => "network#switch_save", :as => "network_switch_save"
  post "network/save" => "network#save", :as => "network_save"

  post "signup/create" => "signup#create", :as => "signup_create"
  get "signup/success" => "signup#success", :as => "signup_success"
  get "signup/:invitation_token" => "signup#new", :as => "signup_with_token"

  # marketing routes
  #post "pilot_signups/:id" => "pilot_signups#destroy", :as => "signup_delete"
  #get "download/ebook" => "download#ebook", :as => "download_ebook"
  #get "download/faq" => "download#faq", :as => "download_faq"
  #get "admin" => "pilot_signups#index", :as => "admin"
  post "signup" => "register#signup", :as => "signup"
  match "product" => "home#product"
  #match "home_new" => "home#home_new", :as => "home_new"

  match 'fb_tab' => "landing#fb_tab", :as => 'fb_tab'
  get 'fb_tab_post' => "landing#fb_tab_post"
  
  resources :comments do
    # the call in app/views/events/_comment.mobile.erb has method: :delete set but it still comes in as get 
    get 'remove', on: :member, as: :destroy
  end
  resources :events do
    delete 'cancel', on: :member
    put 'update_user', on: :member
  end
  resources :messages
  resources :password_resets
  resources :pilot_signups
  resources :posts
  resources :sessions

  match "debugger/:action(/:id)" => "debug", :as => :debug
  
  get "users/current"
  
  # backoffice routes
  namespace :backoffice do
    get '', :to => 'dashboard#index', :as => '/'
    resources :users, :networks, :news, :events, :invitations, :activities, :landpage
  end

  mount Resque::Server, :at => "/resque"
  
  constraints(AgentConstraint) do
   root :to => "mobile#index", :as => "root"
  end
  root :to => "home#index", :as => "root"
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  respond_to :html, :js, :json

  # create signup    
  def signup
     @pilot_signup = PilotSignup.new(params[:pilot_signup])
     @pilot_signup.save
     if @pilot_signup.signup_type == 'ebook'
       cookies[:ebook] = "1"
     elsif @pilot_signup.signup_type == 'pilot'
       cookies[:pilot] = "1"
     end
     respond_with( @pilot_signup, :layout => false )
  end
  
  def new
    network_name = params[:network_for_who] || ""
    network_name += "'s Network" unless params[:network_for_who].blank?
    @network = Network.new( network_for_who: params[:network_for_who], 
                            name:            network_name              )

    
    
    if @current_user = current_user
      @network.users.build( { email:      current_user.email, 
                              last_name:  current_user.last_name,
                              first_name: current_user.first_name } )
      @readonly = true
    else
      @network.users.build( { email:      params[:email] || "" } )
      @readonly = false
    end
    @network.affiliations.build( role:         User::ROLES["initiator"],
                                 relationship: "Caregiver"               )
    @network.users[0].notification = Notification.new(:announcement => true, :post_update => true)
    
    render :action => "new", :layout => "app_no_nav"
  end


  
  # create community network
  def create
    #if user email already exists
    user = User.find_by_email(params[:network][:users_attributes]["0"][:email])
    logger.info ">>0 #{user.try :email}"
    if user
      # if correct password for email
      if user.authenticate(params[:network][:users_attributes]["0"][:password])
        logger.info ">>1 #{user} authed"
        cookies[:auth_token] = user.auth_token
        users_attributes = params[:network].delete("users_attributes")

        @network = Network.new(params[:network])
        if @network.save
          logger.info ">>2 @network saved!"
          session[:landing_email] = nil
          # looks very wrong \/
          @network.affiliations.first.update_attributes( {network_id: @network.id, user_id: user.id })
          user.update_attribute( :network_id, @network.id )
          Resque.enqueue(WelcomeMailer, user.id)
          redirect_to register_success_path
        else
          logger.info ">>3 network nonsaved"
          @network.users.build( { email:      user.email, 
                                  last_name:  user.last_name,
                                  first_name: user.first_name } )
          @readonly = true
          render action: "new", layout: "app_no_nav"
        end
      else
        logger.info ">>4 #{user} non-authed"
        @network = Network.new(params[:network])
        @network.errors.add(:password, "did not match email address" )
        @current_user = current_user
        render action: "new", layout: "app_no_nav"
      end
    else
      
      # could have param "affiliations_attributes" set to null at some point to have it 
      @network = Network.new(params[:network])
      logger.info ">>5 new user #{params[:network].inspect} "
      if @network.save
        # set the current network of the new user to the new network
        user = @network.users.first
        user.update_attribute(:network_id, @network.id)
        
        @network.affiliations.first.update_attributes( { 
          network_id: @network.id, 
          user_id: user.id,
          relationship: params[:network][:affiliations_attributes]["0"][:relationship],
          role: params[:network][:affiliations_attributes]["0"][:role] } )
        
        # hack to fix double affiliation problem
        if @network.affiliations(true).count > 1
          @network.affiliations.last.delete # dont trigger after_destroy's
        end

        
        cookies[:auth_token] = user.auth_token
        Resque.enqueue(WelcomeMailer, user.id)
        if (params[:notification])
          user.notification = Notification.new(:announcement => true, :post_update => true)
        end
                
        redirect_to register_success_path
      else
        render :action => "new", :layout => "app_no_nav"
      end
    end
  end
    
  def success
      render "success", :layout => "app_no_nav"
  end
  
end

app/views/register/new.html.erb
<div id="register_box" >
  <div id="description_div">
  <h3 class="page_title">Create a Caregaroo Network</h3>
  <p class="page_desc">You are about to create a Caregaroo network in two easy steps. The first step is to name the network and identify the person at the center of the network. The second step is to create your account</p>
  </div>

  <%= form_for @network, url: register_path do |f| %>
    <%= render "shared/error_messages", target: @network %>
      
      <div class="clear_format">  
      <%= image_tag "num1.jpg", alt: "Step 1", class: "num_icon" %>
      <div id="vertical_line"></div>  
      <%= f.label :name, "Network name", class: "right_text_with_icon label_space" %> 
      <%= f.text_field :name, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off' %>
      <%= f.label :network_for_who, "Who is the network for?", class: "right_text_with_icon label_space" %> 
      <%= f.text_field :network_for_who, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off' %>    
      </div>
      <br/><br/>
    
    <div class="clear_format">
      <%= image_tag "num2.jpg", alt: "Step 2", class: "num_icon" %>      
      <%= f.fields_for :users do |u| %>
        <!-- hidden timezone pick -->
        <div style="display:none;">
          <%= u.time_zone_select( 'time_zone', [], default: 10) %>
          <script type="text/javascript">
            CG2.TimeZone.setSelect('#network_users_attributes_0_time_zone')
          </script>
        </div>
      
        <%= u.label :email, "Your email", class: "right_text_with_icon label_space" %>
        <%= u.text_field :email, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off', readonly: @current_user.present?, :value => (@network.users[0].try(:email).blank? ? session[:landing_email] : @network.users[0].try(:email)) %>
        <% if @current_user %><p class="right_text_with_icon note_text"><%= link_to "(log out)", logout_path %></p><% end %>
        <%= u.label :first_name, "Your first name", class: "right_text_with_icon label_space" %>
        <%= u.text_field :first_name, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off', readonly: @current_user.present? %>
        <%= u.label :last_name, "Your last name", class: "right_text_with_icon label_space" %>
        <%= u.text_field :last_name, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off', readonly: @current_user.present? %><br class="clear_format"/><br/>
        <%= u.label :password, class: "right_text_with_icon label_space" %>
        <%= u.password_field :password, size: 35, class: "right_text_with_icon" %>
        <p class="right_text_with_icon note_text">Password must contain at least 6 characters.</p>
      <% end %>
      <%= f.fields_for :affiliations do |a| %>
        <%= a.label :relationship, 'Relationship to the person at the centre of network', class: "right_text_with_icon label_space" %>
        <%= a.text_field :relationship, size: 35, class: "right_text_with_icon field_space", autocomplete: 'off' %>
        <%= a.hidden_field :role, value: User::ROLES["initiator"] %>
      <% end %>
    </div>

    <div class="clear_format">
      <br/>
      
      <div class="right_text_with_icon">
      </div>
        <div class="right_text_with_icon">
          <%= hidden_field_tag :notification, 1 %>
          <%= hidden_field_tag :tos, 1 %>
        By signing up, I have read and agree to the <a class="tos" href="https://caregaroo.zendesk.com/entries/21360183-terms-of-services" target="_blank">Terms of Services</a>.
      </div>
      
      <br style="clear:both"/>
       <%= f.submit "Create Network", class: "form_button", id: "create_btn"%> 
     </div>

  <% end %>

</div>

app/views/register/signup.js.erb
var el = $('#downloadebook');

<% if @pilot_signup.errors.any? %>

  // Create a list of errors
  var errors = $('<ul />');

  <% @pilot_signup.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>

  // Display errors on form
  el.find('.errors').html(errors);

<% else %>	
	<% if @pilot_signup.signup_type == 'quick_signup' %>
		<% if params[:quick_signup] == 'top' %>
			$('.top_signup_email').val('THANK YOU FOR PARTICIPATING')
		<% elsif params[:quick_signup] == 'bottom' %>
			$('.bottom_signup_email').val('THANK YOU FOR PARTICIPATING')
		<% end %>	
	<% elsif @pilot_signup.signup_type == 'demo' %>
			$('#demo').html('<form id="demoSuccess" method="post" action="#"><p class="successMsg">Thank you!<br/>We will contact you to arrange a demo.</p><input type="submit" value="Okay" name="okay"></form>')
	<% elsif @pilot_signup.signup_type == 'pilot' %>	
		$('#pilot').html('<form id="pilotsuccess_form" method="post" action="#"><p class="successMsg">Thank you!<br/>for signing-up!<br/>We will contact you when the pilot program begins.</p><input type="submit" value="Okay" name="okay"></form>')
	<% elsif @pilot_signup.signup_type == 'ebook' %>	
		$.fancybox.close()
		window.location = 'download/ebook'
	<% end %>
	
<% end %>

app/views/register/success.html.erb
<div id="register_success_box" >
	<br/>
	<center><h3 class="page_title">Your network has been successfully created!</h3></center>
	<br/>
	<%= link_to "Back to Home", news_path, :id=>"register_success_btn",:class=>"orange_button_link" %>

</div>